# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :zabbix, :primary => true do |zabbix|
    zabbix.vm.box = "zabbix"
    zabbix.vm.network :private_network, ip: "192.168.50.4"

    zabbix.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", 1024]
    end
  end
end

