# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :haproxy, :primary => true do |haproxy|
    haproxy.vm.box = "haproxy"
    haproxy.vm.network :private_network, ip: "192.168.51.4"

    haproxy.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", 1024]
    end
  end
end